### Get departments
GET http://localhost:3000/api/employees

### Get department By Id
GET http://localhost:3000/api/employee/2

### Add department
POST http://localhost:3000/api/employee
Content-Type: application/json

{
    "first_name" : "Agus",
    "last_name" : "Setiawan",
    "email" : "AGUS",
    "phone_number" : "087885159098",
    "hire_date" : "2020-03-12T13:00:00.000Z",
    "salary" : "16000",
    "commission_pct" : "0.1",
    "job_id" : "IT_PROG",
    "manager_id" : 120,
    "department_id" : 90
}

### Update department
PUT http://localhost:3000/api/employee/2
Content-Type: application/json

{
    "first_name" : "AgusS",
    "last_name" : "Setiawans",
    "email" : "AGUSS",
    "phone_number" : "0878xxxxxxx",
    "hire_date" : "2022-03-12T13:00:00.000Z",
    "salary" : "18000",
    "commission_pct" : "1.1",
    "job_id" : "IT_PROG",
    "manager_id" : 110,
    "department_id" : 90
}

### Delete department
DELETE http://localhost:3000/api/employee/2